export default [
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
  {
    price: 260000,
    number: "08764245",
    date: "04 March 2022",
    type: "'Villa For Sale",
    m2: 350,
    age: 13,
    rooms: "5+2",
    floors: "3",
    heating: "Natural Gas",
    bathrooms: 4,
    furnished: "Yes",
    status: "Empty",
    cite: "No",
    dues: "Unspecified",
    deed: "Ownership",
    Owner: "Bixos",
    sold: false,
  },
];
