export default [
  {
    id: 1,
    price: 3000000,
    name: "Downton Abbey ",
    houseSquareMetre: 150,
    landSquareMetre: 300,
    numberOfFloors: 2,
    adress: "Bixos City",
    buildYear: 2010,
    architectureStyle: "Victorian",
    forSale: true,
    occupied: false,
    furniture: false,
    rooms: {
      bedroom: 5,
      bath: {
        private: 2,
        ensuite: 1,
      },
    },
    features: [
      { name: "Terrace", icon: "" },
      { name: "Garage", icon: "" },
      { name: "Fiber", icon: "" },
      { name: "CCTV", icon: "" },
      { name: "Patio", icon: "" },
      { name: "Pool", icon: "" },
    ],
  },
  {
    id: 1,
    price: 3000000,
    name: "Downton Abbey ",
    houseSquareMetre: 150,
    landSquareMetre: 300,
    numberOfFloors: 2,
    adress: "Bixos City",
    buildYear: 2010,
    architectureStyle: "Victorian",
    forSale: true,
    occupied: false,
    furniture: false,
    rooms: {
      bedroom: 5,
      bath: {
        private: 2,
        ensuite: 1,
      },
    },
    features: [
      { name: "Terrace", icon: "" },
      { name: "Garage", icon: "" },
      { name: "Fiber", icon: "" },
      { name: "CCTV", icon: "" },
      { name: "Patio", icon: "" },
      { name: "Pool", icon: "" },
    ],
  },
  {
    id: 1,
    price: 3000000,
    name: "Downton Abbey ",
    houseSquareMetre: 150,
    landSquareMetre: 300,
    numberOfFloors: 2,
    adress: "Bixos City",
    buildYear: 2010,
    architectureStyle: "Victorian",
    forSale: true,
    occupied: false,
    furniture: false,
    rooms: {
      bedroom: 5,
      bath: {
        private: 2,
        ensuite: 1,
      },
    },
    features: [
      { name: "Terrace", icon: "" },
      { name: "Garage", icon: "" },
      { name: "Fiber", icon: "" },
      { name: "CCTV", icon: "" },
      { name: "Patio", icon: "" },
      { name: "Pool", icon: "" },
    ],
  },
  {
    id: 1,
    price: 3000000,
    name: "Downton Abbey ",
    houseSquareMetre: 150,
    landSquareMetre: 300,
    numberOfFloors: 2,
    adress: "Bixos City",
    buildYear: 2010,
    architectureStyle: "Victorian",
    forSale: true,
    occupied: false,
    furniture: false,
    rooms: {
      bedroom: 5,
      bath: {
        private: 2,
        ensuite: 1,
      },
    },
    features: [
      { name: "Terrace", icon: "" },
      { name: "Garage", icon: "" },
      { name: "Fiber", icon: "" },
      { name: "CCTV", icon: "" },
      { name: "Patio", icon: "" },
      { name: "Pool", icon: "" },
    ],
  },
];
